# Generated by Django 4.1.2 on 2022-11-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SONG_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='Artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SONG_api.artiste'),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='Song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SONG_api.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='Artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SONG_api.artiste'),
        ),
    ]
